application: bethandficus
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /(dump|csv)
  script: wedding.py
  login: admin

- url: /.*
  script: wedding.py
